# Generated by Django 3.0.5 on 2020-06-12 09:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testsuite', '0002_question_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='testsuite.Question'),
        ),
        migrations.CreateModel(
            name='TestSuiteRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_run', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('test_suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_suite_runs', to='testsuite.TestSuite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_suite_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
