# Generated by Django 3.0.5 on 2020-06-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0003_auto_20200612_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuiterun',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Started')], default=1),
        ),
    ]
