# Generated by Django 3.0.5 on 2020-06-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0004_testsuiterun_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='covers'),
        ),
    ]
