# Generated by Django 3.0.5 on 2020-06-14 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0005_testsuite_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuiterun',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
