# Generated by Django 3.0.5 on 2020-06-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0007_auto_20200614_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
