# Generated by Django 3.0.5 on 2020-06-14 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0008_variant_correct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='num_variant_limit',
            new_name='Minimal number of variants',
        ),
    ]
