# Generated by Django 3.0.5 on 2020-06-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0009_auto_20200614_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuite',
            name='image',
            field=models.ImageField(default='default.png', upload_to='covers'),
        ),
    ]
