# Generated by Django 3.0.5 on 2020-06-17 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0010_auto_20200616_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Minimal number of variants',
        ),
        migrations.AddField(
            model_name='question',
            name='num_variant_min_limit',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(6)], verbose_name='Minimal number of variants'),
        ),
    ]
