# Generated by Django 3.0.5 on 2020-06-17 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0011_auto_20200617_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuiteRunDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsuite.Question')),
                ('test_suite_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='testsuite.TestSuiteRun')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='testsuite.Variant')),
            ],
        ),
    ]
