# Generated by Django 3.0.5 on 2020-06-17 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0012_testsuiterundetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='num_variant_min_limit',
        ),
    ]
