# Generated by Django 3.0.5 on 2020-06-21 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0015_question_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRunDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='testsuite.Answer')),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='test_suite',
            new_name='test',
        ),
        migrations.DeleteModel(
            name='TestRunDetails',
        ),
        migrations.AddField(
            model_name='testrundetail',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testsuite.Question'),
        ),
        migrations.AddField(
            model_name='testrundetail',
            name='test_suite_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='testsuite.TestRun'),
        ),
    ]
