# Generated by Django 3.0.5 on 2020-06-21 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0016_auto_20200621_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number2',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
