# Generated by Django 3.0.5 on 2020-06-21 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0017_auto_20200621_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='number2',
        ),
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
