# Generated by Django 3.0.5 on 2020-06-24 16:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testsuite', '0018_auto_20200621_0946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestRun',
            new_name='TestResult',
        ),
        migrations.RenameModel(
            old_name='TestRunDetail',
            new_name='TestResultDetail',
        ),
    ]
