# Generated by Django 3.0.5 on 2020-06-24 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0020_auto_20200624_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='score',
            new_name='avr_score',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='state',
        ),
    ]
