# Generated by Django 3.0.5 on 2020-06-24 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0021_auto_20200624_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresultdetail',
            name='test_suite_run',
        ),
        migrations.AddField(
            model_name='testresultdetail',
            name='test_result',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_result_details', to='testsuite.TestResult'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testresultdetail',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsuite.Answer'),
        ),
    ]
