# Generated by Django 3.0.5 on 2020-06-24 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0022_auto_20200624_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='avr_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
