# Generated by Django 3.0.7 on 2020-07-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0025_testresult_is_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestSale',
        ),
    ]
